apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: ridebooking
data:
  DB_HOST: "prod-ridebooking-db.cup04qs62a2f.us-east-1.rds.amazonaws.com"
  DB_USERNAME: "ride_admin"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ride-service-config
  namespace: ridebooking
data:
  DB_HOST: "prod-ridebooking-db.cup04qs62a2f.us-east-1.rds.amazonaws.com"
  DB_USERNAME: "ride_admin"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: ridebooking
data:
  DB_HOST: "prod-ridebooking-db.cup04qs62a2f.us-east-1.rds.amazonaws.com"
  DB_USERNAME: "ride_admin"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: ridebooking
data:
  DB_HOST: "prod-ridebooking-db.cup04qs62a2f.us-east-1.rds.amazonaws.com"
  DB_USERNAME: "ride_admin"
