apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-secret
  namespace: ridebooking
spec:
  data:
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: "prod/ridebooking/db"
        property: password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-runtime-secret
  namespace: ridebooking
spec:
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: "prod/ridebooking/app"
        property: jwt_secret
    - secretKey: APP_ADMIN_PASSWORD
      remoteRef:
        key: "prod/ridebooking/app"
        property: admin_password
    - secretKey: AWS_REGION
      remoteRef:
        key: "prod/ridebooking/app"
        property: aws_region
    - secretKey: AWS_SQS_PAYMENT_QUEUE_URL
      remoteRef:
        key: "prod/ridebooking/app"
        property: payment_queue_url
    - secretKey: AWS_SQS_NOTIFICATION_QUEUE_URL
      remoteRef:
        key: "prod/ridebooking/app"
        property: notification_queue_url
    - secretKey: AWS_SES_FROM
      remoteRef:
        key: "prod/ridebooking/app"
        property: ses_from
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: ridebooking
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: ridebooking-sa

