apiVersion: apps/v1
kind: Deployment
metadata:
  name: ride-service
  namespace: ridebooking
  labels:
    app: ride-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ride-service
  template:
    metadata:
      labels:
        app: ride-service
    spec:
      serviceAccountName: ridebooking-sa
      containers:
        - name: ride-service
          image: ride-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          envFrom:
            - configMapRef:
                name: ride-service-config
            - secretRef:
                name: app-runtime-secret
                optional: true
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MYSQL_ROOT_PASSWORD
