apiVersion: v1
kind: Service
metadata:
  name: ride-service
  namespace: ridebooking
spec:
  selector:
    app: ride-service
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
  type: ClusterIP
