apiVersion: v1
kind: ServiceAccount
metadata:
  name: ridebooking-sa
  namespace: ridebooking
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<account_id>:role/staging-ridebooking-secrets-role
