apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-runtime-secret
  namespace: ridebooking
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: app-runtime-secret
    creationPolicy: Owner
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: "<environment>/ridebooking/app"
        property: jwt_secret
    - secretKey: APP_ADMIN_PASSWORD
      remoteRef:
        key: "<environment>/ridebooking/app"
        property: admin_password
    - secretKey: AWS_REGION
      remoteRef:
        key: "<environment>/ridebooking/app"
        property: aws_region
    - secretKey: AWS_SQS_PAYMENT_QUEUE_URL
      remoteRef:
        key: "<environment>/ridebooking/app"
        property: payment_queue_url
    - secretKey: AWS_SQS_NOTIFICATION_QUEUE_URL
      remoteRef:
        key: "<environment>/ridebooking/app"
        property: notification_queue_url
    - secretKey: AWS_SES_FROM
      remoteRef:
        key: "<environment>/ridebooking/app"
        property: ses_from
