apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ../../base/ingress
- ../../base/external-secrets
- ../../base/autoscaling
- ../../base/monitoring

patches:
- path: patches/db-host-patch.yaml
- path: patches/aws-serviceaccount-patch.yaml
- path: patches/external-secrets-patch.yaml

images:
- name: auth-service
  newName: 688978191806.dkr.ecr.us-east-1.amazonaws.com/prod-auth-service
  newTag: af6d6d091df1a9e4d1b2af05b0dd62a35d1b58dd
- name: notification-service
  newName: 688978191806.dkr.ecr.us-east-1.amazonaws.com/prod-notification-service
  newTag: 036bcd41ff2344dbc1ce6b000513c12850180b47
- name: payment-service
  newName: 688978191806.dkr.ecr.us-east-1.amazonaws.com/prod-payment-service
  newTag: 036bcd41ff2344dbc1ce6b000513c12850180b47
- name: ride-service
  newName: 688978191806.dkr.ecr.us-east-1.amazonaws.com/prod-ride-service
  newTag: 036bcd41ff2344dbc1ce6b000513c12850180b47
