apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../base/ingress
  - ../../base/external-secrets

patches:
  - path: patches/db-host-patch.yaml
  - path: patches/aws-serviceaccount-patch.yaml
  - path: patches/external-secrets-patch.yaml

images:
  - name: auth-service
    newName: <account_id>.dkr.ecr.us-east-1.amazonaws.com/prod-auth-service
    newTag: prod
  - name: ride-service
    newName: <account_id>.dkr.ecr.us-east-1.amazonaws.com/prod-ride-service
    newTag: prod
  - name: payment-service
    newName: <account_id>.dkr.ecr.us-east-1.amazonaws.com/prod-payment-service
    newTag: prod
  - name: notification-service
    newName: <account_id>.dkr.ecr.us-east-1.amazonaws.com/prod-notification-service
    newTag: prod

replicas:
  - name: auth-service
    count: 2
  - name: ride-service
    count: 2
  - name: payment-service
    count: 2
  - name: notification-service
    count: 2
