apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ridebooking
  namespace: argocd
spec:
  description: Ride Booking production project

  sourceRepos:
    - https://github.com/Sulakshani99/ride-booking-app-Kubernetes-deployment.git

  destinations:
    - namespace: ridebooking
      server: https://kubernetes.default.svc

    - namespace: monitoring
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace