apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: ridebooking
data:
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_USERNAME: root
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_SHOW_SQL: "false"
