apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../base/ingress
  - ../../base/external-secrets

patches:
  - path: patches/rds-config-patch.yaml
  - path: patches/aws-serviceaccount-patch.yaml
  - path: patches/external-secrets-patch.yaml

images:
  - name: auth-service
    newName: 688978191806.dkr.ecr.us-east-1.amazonaws.com/staging-auth-service
    newTag: staging
  - name: ride-service
    newName: 688978191806.dkr.ecr.us-east-1.amazonaws.com/staging-ride-service
    newTag: staging
  - name: payment-service
    newName: 688978191806.dkr.ecr.us-east-1.amazonaws.com/staging-payment-service
    newTag: staging
  - name: notification-service
    newName: 688978191806.dkr.ecr.us-east-1.amazonaws.com/staging-notification-service
    newTag: staging

replicas:
  - name: auth-service
    count: 1
  - name: ride-service
    count: 1
  - name: payment-service
    count: 1
  - name: notification-service
    count: 1
