apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: ridebooking
spec:
  selector:
    app: payment-service
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
  type: ClusterIP
